<?php

/**
 * #ddev-generated by ddev-upsun add-on
 * If you want to edit this file (not recommended) remove the line above.
 * EnvironmentLoader
 *
 * Loads additional DDEV environment variables from temporary file.
 */

declare(strict_types=1);

namespace Upsun;

/**
 * Environment Variables Loader
 *
 * TEMPORARY WORKAROUND: Loads DDEV environment variables from .env.temp file
 * TODO: Remove when DDEV provides these variables directly to PHP add-on context
 */
class EnvironmentLoader
{
    /**
     * Load additional DDEV environment variables from temp file
     *
     * @param string $tempFile Path to temporary environment file (default: .env.temp)
     */
    public static function loadDdevEnvironment(string $tempFile = '.env.temp'): void
    {
        if (!file_exists($tempFile)) {
            return;
        }

        $envLines = file($tempFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        if ($envLines === false) {
            return;
        }

        foreach ($envLines as $line) {
            if (strpos($line, '=') !== false && !str_starts_with($line, '#')) {
                putenv($line);
            }
        }
    }
}